s = set()
print(type(s))
sl = set([10, 12, 'He', 13])
print(sl)
print(type(sl))
s.add(1)
print(s)
s.add(1)
s.add(2)
print(s)
print('\n', 'Set retains only the unique values')
s1 = s.union({1,2,3})
print(s, s1)
s2 = s.intersection({1,2,3})
print(s2)